version: '2.1'

volumes:
  config:
  adguardhome_work:
  adguardhome_conf:
  tailscale:
    
services:

  # https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant
  homeassistant:
    image: "homeassistant/raspberrypi3-homeassistant:dev"
    ports:
      - "80:8123"
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
    devices:
      - "/dev:/dev"
      
  # https://hub.docker.com/r/causticlab/hass-configurator-docker
  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    restart: always
    ports:
      - "8080:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config

    # https://hub.docker.com/r/adguard/adguardhome
  adguard:
    image: "adguard/adguardhome:beta"
    network_mode: host
    privileged: true
    volumes:
      - 'adguardhome_work:/opt/adguardhome/work:rw'
      - 'adguardhome_conf:/opt/adguardhome/conf:rw'
    command: --host 0.0.0.0 --port 8000 --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /var/run/
    volumes:
      - tailscale:/var/lib/tailscale
